apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-backup-operator
  labels:
    name: etcd-backup-operator
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  replicas: 3
  selector:
    matchLabels:
      name: etcd-backup-operator
  template:
    metadata:
      labels:
        name: etcd-backup-operator
    spec:
      serviceAccount: etcd-operator
      tolerations:
        - key: "multi-az-worker"
          operator: "Equal"
          value: "true"
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: ["etcd-backup-operator"]
              topologyKey: "kubernetes.io/hostname"
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: ["etcd-backup-operator"]
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
      containers:
        - name: etcd-backup-operator
          image: registry.ng.bluemix.net/armada-master/etcd-operator:02cc01028522064335bcdeca582f81da6ae102fb
          command:
            - etcd-backup-operator
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
