apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-operator
  labels:
    name: etcd-operator
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  replicas: 3
  selector:
    matchLabels:
      name: etcd-operator
  template:
    metadata:
      labels:
        name: etcd-operator
      annotations:
        prometheus.io/path: '/metrics'
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      serviceAccount: etcd-operator
      tolerations:
        - key: "multi-az-worker"
          operator: "Equal"
          value: "true"
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: ["etcd-operator"]
              topologyKey: "kubernetes.io/hostname"
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: ["etcd-operator"]
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
      containers:
        - name: etcd-operator
          image: ${ETCD_OPERATOR_IMAGE}
          ports:
            - containerPort: 8080
              name: http
          command:
            - etcd-operator
            - -re-interval=60s
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCD_HEALTHCHECK_IMAGE
              value: ${ETCD_HEALTH_CHECK_IMAGE}
