apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sidecar-backup-privledges
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - "get"
      - "delete"
  - apiGroups:
      - etcd.database.coreos.com
    resources:
      - etcdbackups
    verbs:
      - "*"
