apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etcd-operator
rules:
- apiGroups:
    - etcd.database.coreos.com
  resources:
    - etcdclusters
    - etcdbackups
    - etcdrestores
  verbs:
    - "*"
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - pods/log
  verbs:
    - "*"
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - secrets
    - configmaps
  verbs:
    - "*"
- apiGroups:
    - "batch"
  resources:
    - jobs
  verbs:
    - "*"
