apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-restore-operator
  labels:
    name: etcd-restore-operator
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  replicas: 3
  selector:
    matchLabels:
      name: etcd-restore-operator
  template:
    metadata:
      labels:
        name: etcd-restore-operator
    spec:
      serviceAccount: etcd-operator
      tolerations:
        - key: "multi-az-worker"
          operator: "Equal"
          value: "true"
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: ["etcd-restore-operator"]
              topologyKey: "kubernetes.io/hostname"
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: ["etcd-restore-operator"]
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
      containers:
        - name: etcd-restore-operator
          image: ${ETCD_OPERATOR_IMAGE}
          command:
            - etcd-restore-operator
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CUSTOM_CURL_IMAGE
              value: ${CUSTOM_CURL_IMAGE}
            - name: ETCD_HEALTHCHECK_IMAGE
              value: ${ETCD_HEALTH_CHECK_IMAGE}
