apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sidecar-backup-privledges
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sidecar-backup-privledges
subjects:
  - kind: ServiceAccount
    name: default
