apiVersion: v1
kind: Service
metadata:
  name: etcd-${CLUSTER_ID}-client-service-np
spec:
  ports:
    - name: client
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    etcd_cluster: etcd-${CLUSTER_ID}
  type: NodePort
