kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshift-controller-manager
  template:
    metadata:
      labels:
        app: openshift-controller-manager
    spec:
      automountServiceAccountToken: false
      containers:
      - name: openshift-controller-manager
        image: ${OPENSHIFT_CONTROLLER_MANAGER_IMAGE}
        command:
        - "openshift-controller-manager"
        args:
        - "start"
        - "--config=/etc/kubernetes/config.yaml"
        volumeMounts:
        - mountPath: /etc/kubernetes/
          name: secret
      volumes:
      - secret:
          secretName: openshift-controller-manager
        name: secret
