kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-scheduler
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: kube-scheduler
  template:
    metadata:
      labels:
        app: kube-scheduler
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["kube-scheduler"]
              topologyKey: "kubernetes.io/hostname"
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["kube-scheduler"]
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
      automountServiceAccountToken: false
      containers:
      - name: kube-scheduler
        image: ${HYPERKUBE_IMAGE}
        command:
        - hyperkube
        - kube-scheduler
        args:
        - "--config=/etc/kubernetes/config.yaml"
        - "--cert-dir=/var/run/kubernetes"
        - "--port=0"
        - "--authentication-kubeconfig=/etc/kubernetes/kubeconfig"
        - "--authorization-kubeconfig=/etc/kubernetes/kubeconfig"
        - "-v=2"
        volumeMounts:
        - mountPath: /etc/kubernetes/
          name: secret
        - mountPath: /var/run/kubernetes/
          name: cert
        workDir: /var/run/kubernetes
      volumes:
      - secret:
          secretName: kube-scheduler
        name: secret
      - emptyDir: {}
        name: cert
