---
- name: Create Workers
  hosts: localhost
  gather_facts: false
  vars:
    servers:
    - user-worker-0
    - user-worker-1
  tasks:
  - name: ensure worker instances do not already exist
    os_server:
      state: absent
      name: "{{ item }}"
      wait: no
    with_items: "{{ servers }}"
  - name: create workers instances
    os_server:
      state: present
      name: "{{ item }}"
      image: rhcos
      key_name: yubikey
      flavor: worker
      network: external
      wait: no
      userdata: "{{ lookup('file', '../../ignition-generator/bootstrap-final.ign') | string }}"
    with_items: "{{ servers }}"
