kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-oauthserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openshift-oauthserver
  template:
    metadata:
      labels:
        app: openshift-oauthserver
    spec:
      automountServiceAccountToken: false
      containers:
        - name: openshift-oauthserver
          image: ${OPENSHIFT_OAUTHSERVER_IMAGE}
          args:
            - "osinserver"
            - "--config=/etc/kubernetes/config.yaml"
          volumeMounts:
            - mountPath: /etc/kubernetes/
              name: secret
            - mountPath: /var/run/kubernetes
              name: logs
            - mountPath: /var/config/system/secrets/v4-0-config-system-session
              name: v4-0-config-system-session
              readOnly: true
            - mountPath: /var/config/system/secrets/v4-0-config-system-ocp-branding-template
              name: v4-0-config-system-ocp-branding-template
              readOnly: true
          workingDir: /var/run/kubernetes
      volumes:
      - emptyDir: {}
        name: logs
      - name: secret
        secret:
          defaultMode: 420
          secretName: openshift-oauthserver
      - name: v4-0-config-system-session
        secret:
          defaultMode: 420
          items:
            - key: v4-0-config-system-session
              path: v4-0-config-system-session
          secretName: v4-0-config-system-session
      - name: v4-0-config-system-ocp-branding-template
        secret:
          defaultMode: 420
          items:
            - key: login.html
              path: login.html
            - key: providers.html
              path: providers.html
            - key: errors.html
              path: errors.html
          secretName: v4-0-config-system-ocp-branding-template
