apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-version-operator
spec:
  selector:
    matchLabels:
      k8s-app: cluster-version-operator
  strategy:
    type: Recreate
  template:
    metadata:
      name: cluster-version-operator
      labels:
        k8s-app: cluster-version-operator
    spec:
      containers:
      - name: cluster-version-operator
        image: quay.io/csrwng/release:hosted
        imagePullPolicy: Always
        args:
          - "start"
          - "--release-image=quay.io/csrwng/release:hosted"
          - "--enable-auto-update=false"
          - "--enable-default-cluster-version=true"
          - "--kubeconfig=/etc/kubernetes/kubeconfig"
          - "--v=4"
          - "--exclude-manifests=.*"
          - "--include-manifests=.*_cluster-network-operator_.*"
          - "--include-manifests=.*_dns-operator_.*"
          - "--include-manifests=.*_console-operator_.*"
          - "--include-manifests=.*_cluster-samples-operator_.*"
          - "--include-manifests=.*_cluster-node-tuning-operator_.*"
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
          - mountPath: /etc/cvo/updatepayloads
            name: etc-cvo-updatepayloads
            readOnly: true
          - mountPath: /etc/kubernetes
            name: secrets
            readOnly: true
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      volumes:
        - name: etc-cvo-updatepayloads
          emptyDir: {}
        - name: secrets
          secret:
            secretName: cluster-version-operator
